services:
  auth-service:
    container_name: auth-service
    build: 
      context: ./auth-service
    ports:
      - 8080:8080
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 50M
  account-service:
    container_name: account-service
    build: 
      context: ./account-service
    ports:
      - 8081:8080
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 50M
  db:
    container_name: db
    build: 
      context: ./db
    restart: always
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "123Abc!@#"
  message-broker:
    container_name: message-broker
    image: rabbitmq:3-management
    restart: always
    volumes:
      - ./broker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./broker/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
    environment:
      RABBITMQ_DEFAULT_USER: broker_user
      RABBITMQ_DEFAULT_PASS: Abc6666