version: '3'
services:
  auth-service:
    container_name: auth-service
    build: 
      context: ./auth-service
    ports:
      - 8080:8080
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 50M
  account-service:
    container_name: account-service
    build: 
      context: ./account-service
    ports:
      - 8081:8080
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 50M
